### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Pinakin-odoo** [OpenPrinting/pycups#12]
I installed library but when my code use it, it gives me following error. Anyone have idea what is problem here. (I installed library in standard way no customization)

File "/usr/local/lib/python2.7/dist-packages/cups/__init__.py", line 8
    def generate(self) -> string:
                       ^
SyntaxError: invalid syntax

**Comment by lalo-uy** [comment]
Same to me on raspibian Stretch

**Comment by vvzvlad** [comment]
It's also relevant to me.

**Comment by eicher31** [comment]
Same to me on Ubtuntu 19.04

**Comment by zdohnal** [comment]
Hi all,

I would like to say several things:
1) python2 is no longer supported even by python upstream (since 2020-01-01), so I will follow their example.
2) I don't know if any distribution already dropped system-config-printer, but if s-c-p is available than pycups should be packaged as well. If there is something you need from current master branch, distro maintainers is able to backport it for you or I can release new version, so they can directly download new sources. Please tell me if it is needed.
3) I tried to compile pycups in Fedora 32 - after I install necessary build dependencies (cups-devel, python3-devel, gcc), I'll do 'make' and 'sudo make install' in sources. 'import cups' in python3 script works afterwards.

I don't have any __init__.py file in python site-packages directory.

I will update the README accordingly.
