### ISSUE TITLE
(1280, 'No such file or directory')

### ISSUE THREAD

**Issue by doudz** [OpenPrinting/pycups#13]
Problem on Ubuntu 18.04 when printing on remote cups
problem with 1.9.73, 1.9.74 
ubuntu 18.04 use libcups2  version 2.2.7-1ubuntu2.7

Works perfectly on Ubuntu 16.04 and Ubuntu 19.04

```
In [1]: import cups
In [2]: c = cups.Connection('192.168.201.203')
In [3]: c.printFile('OAIM39', os.path.abspath('test.pdf'), 'test', {})
IPPError                                  Traceback (most recent call last)
<ipython-input-5-54feaa379875> in <module>()
----> 1 c.printFile('OAIM39', os.path.abspath('test.pdf'), 'test', {})

IPPError: (1280, 'No such file or directory')

```

**Comment by zdohnal** [comment]
Hi all,
actually, it is not python-cups error - printFile gets an error from CUPS server as internal-server-error. If you check the debug logs on server, you see that the client (printFile method) gets "Forbidden" on the server.
It can be a bug or misconfiguration in CUPS, because the CUPS API behaves the same way. Please report the issue to CUPS upstream.
