### ISSUE TITLE
Driverless printing when create print queue

### ISSUE THREAD

**Issue by isc-yzheng** [OpenPrinting/pycups#34]
in command line we can do: lpadmin -p <printqueue> -E -v <uri> -m everywhere
                                        or: lpadmin -p <printqueue> -E -v <uri> -m driverless:<uri>
to enable driverless printing. But I didn't see there's any parameter in addPrinter() method that can achieve that.
Is there any way we can achieve driverless printing in pycups?

**Comment by zdohnal** [comment]
Hi,

unfortunately, driverless printing hasn't been implemented in python-cups yet.

To be honest, I maintain python-cups because it is needed by system-config-printer - and once modern Linux printing architecture (modern CUPS+Printer Applications) is implemented, there will be no need for system-config-printer, so I don't plan spending time on enhancing python-cups.

However, I'm fine with accepting PRs or adding someone as a collaborator on the project.
