### ISSUE TITLE
["printer-state-message"] always return empty

### ISSUE THREAD

**Issue by arzakmiftakhul** [OpenPrinting/pycups#36]
Hi, I try to get message when I'm printing some pdf file. I want to know if paper or ink out, but `['printer-state-message']` always return empty and  `['printer-state-reasons']` retun `none`.
this is my code to get message:
```
import cups

conn = cups.Connection ()
printers = conn.getPrinters ()
epson_printer = printers["EPSON_L120_Series"]
print(epson_printer['printer-state-message'])
print(epson_printer['printer-state-reasons'])
```

print command via terminal :
```
lp -d EPSON_L120_Series test.pdf
```

I use Ubuntu 20.04.2.LTS, python 3.8.10, cups 2.3.1

**Comment by zdohnal** [comment]
Hi,

IMO it is an expected behavior. I was watching cupsd in gdb when I called ```conn.getPrinters()```, and printer-state-message and printer-state-reasons was empty in cupsd as well.

cupsd sets printer-state-message and printer-state-reasons only if some error happened.

Are you able to verify that the printer-state-message and printer-state-reasons for your printer in global array Printers in cupsd are filled?

**Comment by arzakmiftakhul** [comment]
Thanks, I disconnected printer and `['printer-state-message']` return `Unplugged or turned off`. Yups, it will return message if some error happened, but if no paper  it is not recognized as an error so I can't get any message. Is any function to get message if no paper or ink?

**Comment by arzakmiftakhul** [comment]
this https://github.com/apple/cups/issues/5445#issuecomment-916214116 said that it depend on printer driver, thanks.
